version: "3"
services:

  hub:
    image: selenium/hub:3.141.0
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=10
      - GRID_BROWSER_TIMEOUT=0
      - GRID_JETTY_MAX_THREADS=300
      
  chrome:
    image: selenium/node-chrome-debug:3.141.0
    depends_on:
      - hub
    environment: 
      - HUB_HOST=hub
      - NODE_MAX_INSTANCES=4
      - NODE_JETTY_MAX_THREADS=300
      - NODE_MAX_SESSION=4
      
    ports:
      - "5000:5900"

     
  firefox:
    image: selenium/node-firefox-debug:3.141.0
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - NODE_JETTY_MAX_THREADS=300
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    ports:
      - "4000:5900"
    volumes:
      - /dev/shm:/dev/shm

  test_1:
    image: myimage:latest
    depends_on:
    - hub 
    image: myimage:latest
    depends_on:
    - hub 
    - firefox
    - firefox
    - chrome
    environment:
    - HUB_HOST=hub
    - BROWSER=chrome
    - MODULE=test_1.py
    volumes:
      - ../test_1:/usr/app/test_1
  test_2:
    - chrome
    environment:
    - HUB_HOST=hub
    - BROWSER=firefox
    - MODULE=test_2.py
    volumes:
      - ../test_2:/usr/app/test_2




