version: "3"
services:
  hub:
    image: selenium/hub:3.141.0
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=10
      - GRID_BROWSER_TIMEOUT=0
      - GRID_JETTY_MAX_THREADS=300
      
  chrome:
    image: selenium/node-chrome-debug:3.141.0
    depends_on:
      - hub
    environment: 
      - HUB_HOST=hub
      - NODE_MAX_INSTANCES=4
      - NODE_JETTY_MAX_THREADS=300
      - NODE_MAX_SESSION=4
      
    ports:
      - "5000:5900"

     
  firefox:
    image: selenium/node-firefox-debug:3.141.0
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - NODE_JETTY_MAX_THREADS=300
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    ports:
      - "4000:5900"
    volumes:
      - /dev/shm:/dev/shm




  test_1-module:
    build:
      context: ./module1
      dockerfile: ./Dockerfile.test
      
    depends_on:
      - hub 
      - firefox
      - chrome

    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=test_1.py
    volumes:
      - ./module1:/usr/app
   
  test_2-module:
    build:
      context: ./module2
      dockerfile: ./Dockerfile.test
      
    depends_on:
      - hub 
      - firefox
      - chrome

    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=test_2.py
    volumes:
      - ./module2:/usr/app


